### ISSUE TITLE
[PE-D] Any kind of input is accepted for the DAY parameter

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-4/tp#102]
I can input any kind of string input for the day parameter and the application will accept as it is. 

Shudn't <DAY> be accepted Monday, Tuesday, ..., Sunday as input?

When I see my task again, it shows the day as the parameter I put in which is foo.

![image.png](https://raw.githubusercontent.com/yuzhongng/ped/main/files/b6d1bb7b-158d-49b4-ba66-33243e6f00f5.png)

![image.png](https://raw.githubusercontent.com/yuzhongng/ped/main/files/a30df6f0-09da-458f-83c7-46e481eba81f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yuzhongng/ped#3

**Comment by mathanmahe** [comment]
Related to #97, will be fixed in v2.1.
