### ISSUE TITLE
[PE-D] No empty attribute input check for add item in contacts_manager

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-4/tp#117]
Feature is empty when add item in contacts_manager

![image.png](https://raw.githubusercontent.com/LI-XINYI1/ped/main/files/17d1a86b-1aad-4298-b199-5289ccb938b1.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: LI-XINYI1/ped#5

**Comment by wli-linda** [comment]
Duplicate issue as #118. Also might clarify in documentation that certain fields are optional, undecided.
