### ISSUE TITLE
[PE-D] Exit the edit method directly when error input occur in contact manager

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-4/tp#120]
Directly exit the edit method, with an inappropriate message sent: " Okay, I've updated the information of this contact: ", even with no changes

![image.png](https://raw.githubusercontent.com/LI-XINYI1/ped/main/files/ad01cc21-9e1f-4c13-86b7-c094dbbffa18.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: LI-XINYI1/ped#8

**Comment by wli-linda** [comment]
This was unexpected... Maybe not exiting the method early enough, not too sure, will double check code.
