### ISSUE TITLE
[PE-D] Command summary error

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-4/tp#125]
The format of Edit  shown in UG is only applicable in Study_Manager, but not for contacts_manager

![image.png](https://raw.githubusercontent.com/LI-XINYI1/ped/main/files/92a8dbb9-20c8-44bb-9cd3-27cfd506dd0e.png)

error message in contacts_manager:

![image.png](https://raw.githubusercontent.com/LI-XINYI1/ped/main/files/8c038fd7-7e60-4bba-9f51-ff578d4ba1b7.png)

Should state the edit method seperately for each manager

-------------
Labels: `severity.High` `type.DocumentationBug`
original: LI-XINYI1/ped#13

**Comment by wli-linda** [comment]
Re-routed to new issue #127, which better describes what needs to be done.
