### ISSUE TITLE
Code Review: @mathanmahe

### ISSUE THREAD

**Issue by xseh** [AY2122S2-CS2113-F10-4/tp#90]
@mathanmahe

**src/main/java/seedu/allonus/modules/StudyManager.java:** 
1. Line 72 - 84: Minimise Scope of Variables
2. Line 86: 139: Avoid Long Methods, avoid complicated expressions, consider further SLAPping the method
3. Line 157: Consider writing the comment to the reader instead
4. Line 166, 173: Consider deleting dead code
5. Line 186: Consider deleting dead code

Screenshots:
1. ![image](https://user-images.githubusercontent.com/39018497/161006438-f08abce2-ae6d-4149-855d-82142375dfa8.png)
2. ![image](https://user-images.githubusercontent.com/39018497/161006764-2708543f-eade-4bf6-8dcc-1a8d9411ac3c.png)
3. ![image](https://user-images.githubusercontent.com/39018497/161007006-6198d124-cd5c-4212-bcd7-ed37cc4f6406.png)
4. ![image](https://user-images.githubusercontent.com/39018497/161007349-c718656b-87e5-4af7-9b2e-220721b795e7.png)
6. ![image](https://user-images.githubusercontent.com/39018497/161007416-eca430d6-e44c-4ee6-b132-a26ef1606a74.png)

----

**src/main/java/seedu/allonus/modules/Module.java:** 
1. Line 74-78: Avoid complicated expressions

**Screenshots:** 
1. ![image](https://user-images.githubusercontent.com/39018497/161007738-0bb21719-39ee-4f15-b699-d53df77d8d92.png)

**Comment by mathanmahe** [comment]
Hi I am using global variables so I can break down easily into various methods. If I change the scope I would not be able to extract methods due to many variables they are dealing with. In this case is a higher scope accepted?

**Comment by xseh** [comment]
Hi Mathan,  You can consider restructuring the code, otherwise its okay. It just a consideration to keep in mind.  Regards, Xin Ru From: mathanmaheSent: Friday, 1 April 2022 09:57To: AY2122S2-CS2113-F10-4/tpCc: Xin Ru; AuthorSubject: Re: [AY2122S2-CS2113-F10-4/tp] Code Review: @mathanmahe (Issue #90) Hi I am using global variables so I can break down easily into various methods. If I change the scope I would not be able to extract methods due to many variables they are dealing with. In this case is a higher scope accepted?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
