### ISSUE TITLE
Code Review: @YitHien

### ISSUE THREAD

**Issue by xseh** [AY2122S2-CS2113-F10-4/tp#92]
@YitHien

**src/main/java/seedu/allonus/expense/ExpenseTracker.java:** 
1. Line 62: plus sign can be moved into previous line
2. Line 106: Avoid complicated expressions
3. Line 151: Consider a more meaningful variable name (e.g. Expense expense)
4. Line 205 - 242: Consider SLAPping the method farther to avoid long methods and deep nesting, avoid magic literals
5. Line 260, 261: Avoid complicated expressions
6. Line 357 - 375 Consider making the Happy Path Prominent
7. Line 387, 388: Avoid complicated expressions

**Screenshots:** 
1. ![image](https://user-images.githubusercontent.com/39018497/161010972-96242322-fd76-40d9-bb7c-b221efca4e83.png)
2. ![image](https://user-images.githubusercontent.com/39018497/161012000-86876987-eb4e-4f81-a848-ae0573319ed0.png)
3. ![image](https://user-images.githubusercontent.com/39018497/161012347-43cf2d80-18b4-4eb2-a398-e92fa9604d08.png)
4. ![image](https://user-images.githubusercontent.com/39018497/161012595-1c8ac811-91e3-4a4d-8339-110c80056f9c.png)
5. ![image](https://user-images.githubusercontent.com/39018497/161012930-eaa6fd74-962e-42ff-a972-469a0c5445b7.png)
6. ![image](https://user-images.githubusercontent.com/39018497/161013272-89c32538-1520-4a40-bced-d2265af49808.png)
7. ![image](https://user-images.githubusercontent.com/39018497/161013459-06bc2ffa-2244-4de9-83c3-35c19053813c.png)

----

**src/main/java/seedu/allonus/expense/ExpenseParser.java**
1. Line 66, 67: Avoid complicated expressions
2. Line 93 - 101: Consider SLAPping further and refactoring the code

**Screenshots:** 
1. ![image](https://user-images.githubusercontent.com/39018497/161013789-96170441-1d8c-4e04-94c0-6210f0fe752c.png)
2. ![image](https://user-images.githubusercontent.com/39018497/161014425-fad1c3bb-889a-486a-9207-7da56577913a.png)

**Comment by YitHien** [comment]
Line 62: Gradle checkstyle does not seem to allow the '+' sign to be on the same line

![image](https://user-images.githubusercontent.com/69446722/161393193-9b22483a-557b-4608-9272-f16f7232d435.png)
